<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
$note=noteForUser($clinicalNoteService,(int)($_GET['id']??0),$currentUser);$patient=$patientService->getPatientById((int)$note['patient_id']);$visitId=noteVisitContext($pdo,$permissionService,$currentUser,(int)$note['patient_id'],$_GET['visit']??$note['visit_id']);
$own=(int)$note['author_id']===(int)$currentUser['id'];$canEdit=$note['note_status']==='Draft'&&($own?$permissionService->canEditOwnNoteDraft((int)$note['patient_id'],$currentUser):$permissionService->canEditAnyNoteDraft((int)$note['patient_id'],$currentUser));$canSign=$note['note_status']==='Draft'&&$permissionService->canSignClinicalNotes((int)$note['patient_id'],$currentUser);$canAmend=in_array($note['note_status'],['Signed','Amended'],true)&&$permissionService->canAmendSignedNotes((int)$note['patient_id'],$currentUser);$canHistory=$permissionService->canViewNoteHistory((int)$note['patient_id'],$currentUser);$canError=$note['note_status']!=='Entered-in-error'&&$permissionService->canMarkNoteEnteredInError((int)$note['patient_id'],$currentUser);
$errors=$_SESSION['validation_errors']??[];$success=$_SESSION['success_message']??null;unset($_SESSION['validation_errors'],$_SESSION['success_message']);$pageTitle='Clinical Note';$moduleStylesheet='/modules/medical_records/assets/medical_records.css';require __DIR__.'/../../../layouts/header.php';require __DIR__.'/../../../layouts/sidebar.php';
?><div class="main-container"><?php require __DIR__.'/../../../layouts/navbar.php';?><main class="content">
<?php if($errors):?><div class="alert-danger"><?=e(implode(' ',$errors))?></div><?php endif;?><?php if($success):?><div class="alert-success"><?=e($success)?></div><?php endif;?>
<div class="card"><div class="card-header"><div><h1><?=e($note['title'])?></h1><p><?=e(noteTypeLabel($note['note_type']))?></p></div><span class="status-badge"><?=e($note['note_status'])?></span></div><div class="summary-grid"><div class="summary-item"><span class="summary-label">Author</span><span class="summary-value"><?=e($note['author_name'])?></span></div><div class="summary-item"><span class="summary-label">Department</span><span class="summary-value"><?=e($note['department_name']??'Not assigned')?></span></div><div class="summary-item"><span class="summary-label">Confidentiality</span><span class="summary-value"><?=e($note['confidentiality_level'])?></span></div><div class="summary-item"><span class="summary-label">Version</span><span class="summary-value"><?=(int)$note['current_version']?></span></div><div class="summary-item"><span class="summary-label">Signed</span><span class="summary-value"><?=e($note['signed_at']??'Not signed')?></span></div></div></div>
<div class="card"><h2>Content</h2><div class="clinical-note-content" style="white-space:pre-wrap"><?=e($note['content'])?></div></div>
<div class="card"><h2>Actions</h2><?php if($canEdit):?><a class="btn-secondary" href="edit.php?id=<?=(int)$note['id']?><?=e(noteContextQuery($visitId))?>">Edit Draft</a><?php endif;?><?php if($canHistory):?><a class="btn-secondary" href="history.php?id=<?=(int)$note['id']?>">Version History</a><?php endif;?><?php if($canAmend):?><a class="btn-secondary" href="amend.php?id=<?=(int)$note['id']?><?=e(noteContextQuery($visitId))?>">Amend</a><?php endif;?>
<?php if($canSign):?><form method="post" action="sign.php" class="inline-form"><?=csrfField()?><input type="hidden" name="id" value="<?=(int)$note['id']?>"><input type="hidden" name="version" value="<?=(int)$note['version']?>"><input type="hidden" name="visit_id" value="<?=(int)($visitId??0)?>"><button class="btn-primary" type="submit">Sign and Lock</button></form><?php endif;?>
<?php if($canError):?><form method="post" action="entered_in_error.php" class="inline-form"><?=csrfField()?><input type="hidden" name="id" value="<?=(int)$note['id']?>"><input type="hidden" name="version" value="<?=(int)$note['version']?>"><input type="hidden" name="visit_id" value="<?=(int)($visitId??0)?>"><input name="reason" maxlength="1000" required placeholder="Entered-in-error reason"><button class="btn-secondary" type="submit">Mark Entered in Error</button></form><?php endif;?></div>
<a href="../chart.php?patient=<?=(int)$note['patient_id']?>&tab=notes<?=e(noteContextQuery($visitId))?>">Back to Clinical Notes</a></main><?php require __DIR__.'/../../../layouts/footer.php';?></div>
