-- Staff profile details and repeatable qualifications for Administration users.

CREATE TABLE IF NOT EXISTS staff_profiles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    surname VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100) NULL,
    title VARCHAR(20) NULL,
    gender VARCHAR(20) NULL,
    date_of_birth DATE NULL,
    place_of_birth VARCHAR(150) NULL,
    marital_status VARCHAR(50) NULL,
    home_town VARCHAR(150) NULL,
    permanent_home_address TEXT NULL,
    residential_address TEXT NULL,
    phone_no VARCHAR(50) NULL,
    personal_email VARCHAR(150) NULL,
    religion VARCHAR(100) NULL,
    national_identity_number VARCHAR(50) NULL,
    first_appointment_date DATE NULL,
    first_appointment_salary_grade VARCHAR(100) NULL,
    employee_no VARCHAR(50) NOT NULL,
    official_email VARCHAR(150) NULL,
    salary_bank VARCHAR(150) NULL,
    salary_bank_account_no VARCHAR(50) NULL,
    next_of_kin1_name VARCHAR(150) NULL,
    next_of_kin1_address TEXT NULL,
    next_of_kin1_date_of_birth DATE NULL,
    next_of_kin1_relationship VARCHAR(100) NULL,
    next_of_kin1_phone VARCHAR(50) NULL,
    next_of_kin2_name VARCHAR(150) NULL,
    next_of_kin2_address TEXT NULL,
    next_of_kin2_date_of_birth DATE NULL,
    next_of_kin2_relationship VARCHAR(100) NULL,
    next_of_kin2_phone VARCHAR(50) NULL,
    created_by INT NULL,
    updated_by INT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_staff_profiles_user (user_id),
    INDEX idx_staff_profiles_employee_no (employee_no),
    INDEX idx_staff_profiles_surname_first (surname, first_name),
    CONSTRAINT fk_staff_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_staff_profiles_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_staff_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_educational_qualifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    staff_profile_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 1,
    school_attended_with_dates TEXT NULL,
    course_of_study VARCHAR(255) NULL,
    certificates_obtained VARCHAR(255) NULL,
    class_of_degree VARCHAR(100) NULL,
    year_of_graduation VARCHAR(20) NULL,
    remarks TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_staff_education_profile_order (staff_profile_id, sort_order),
    CONSTRAINT fk_staff_education_profile FOREIGN KEY (staff_profile_id) REFERENCES staff_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS staff_professional_qualifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    staff_profile_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 1,
    certification_type VARCHAR(150) NULL,
    certificates VARCHAR(255) NULL,
    certification_license_no VARCHAR(100) NULL,
    certification_expiration_date DATE NULL,
    year_attained VARCHAR(20) NULL,
    remarks TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_staff_professional_profile_order (staff_profile_id, sort_order),
    INDEX idx_staff_professional_expiration (certification_expiration_date),
    CONSTRAINT fk_staff_professional_profile FOREIGN KEY (staff_profile_id) REFERENCES staff_profiles(id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
